# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build and push mola

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Login to abcdevreg Registry
      run: echo ${{ secrets.ABCREG_PASSWORD }} | docker login -u ${{ secrets.ABCREG_USERNAME }} --password-stdin abcdevreg.azurecr.io
    - name: Build the latest Docker image to AZURE 
      run: docker build . --file Dockerfile --tag abcdevreg.azurecr.io/nihab/mola-service-api:latest
    - name: Push the latest Docker image to AZURE 
      run: docker push abcdevreg.azurecr.io/nihab/mola-service-api:latest
