# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build mola

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag nihab/mola-service-api:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push nihab/mola-service-api:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag nihab/mola-service-api:latest
    - name: Push the latest Docker image
      run: docker push nihab/mola-service-api:latest
